version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - run:
          name: install packages
          command: yarn install --frozen-lockfile
      - run:
          name: Run Tests
          command: npm run test
  deploy_to_staging:
    docker:
       - image: cimg/node:14.15.4
    working_directory: ~/practical-ci
    steps:
      - checkout
      - run: npm install surge
      - run: yarn install
      - run: yarn build 
      - run:
          name: Deploy to staging
          command: npx surge build/ https://marks-counter-staging.surge.sh
  test_ui_staging:
      docker: 
      - image: circleci/node:10.15.0-jessie-browsers
      steps: 
       - checkout  
       - run: npm install surge
       - run: yarn install
       - run: yarn build
       - run: yarn add --dev --exact puppeteer jest-junit cross-env
       - run:
          name: Run UI Tests
          command: yarn e2e


workflows:
  orb-free-workflow:
    jobs:
      - test
      - deploy_to_staging:
          requires:
            - test
          filters:
            branches:
              only: master
      - test_ui_staging:
          requires:
            - test
            - deploy_to_staging
